### ISSUE TITLE
how to run your script

### ISSUE THREAD

**Issue by ibmbea** [aavmurphy/blogger-oauth-javascript#1]
i hv provided the blogger id, post id, api_key and client id.

how to "execute" the html script? i load it on browser  from local hard disk. it shows error while click sign in button.

did it expect to upload http server to run?
blogger-oauth.html

**Comment by aavmurphy** [comment]
hi. 
it runs in the browser only, no server
in chrome: options | more tools | developer tools | console
i tried in in a browser window, and got 
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').`
i think i've seen this error before, i  think you need to run it as a page on an https website (as it uses oauth), not an http website (which your browser window is)
also, check you've enabled the blogger v3 api on the google cloud console

**Comment by ibmbea** [comment]
hi andrew, thx ur script. i made it run. it should deploy on webserver (e.g. apache 2). it required to register a domain name to include google console api of oauth 2 web client id page. user may make of dyndns to have temporary domain name. I adjust the published post of date to 2022 or later. it is nice.
